source 'https://rubygems.org'

gem 'rake', '10.3.2'
gem 'guard', '2.6.1'
gem 'coffee-script-source', '1.8.0'
gem 'guard-livereload', '2.3.1'
gem 'guard-coffeescript', '1.4.0'
gem 'guard-coffeelint', :git => 'git@github.com:Ahalogy/guard-coffeelint.git'
gem 'guard-ejs', '0.0.1'
gem 'guard-compass', '1.1.0'
gem 'sass', '3.4.5'
gem 'compass', '1.0.1'
gem 'susy', '~> 2.1.3'
gem 'image_optim', '0.17.1'
gem 'scss-lint', '0.29.0'
gem 'sass-globbing', '1.1.1'