# Configuration options.
#
# This config file is only used for development related taks.
# See the Rakefile (or run `bundle exec rake -T`) for tasks that use this information.
themename: test

build_dir: build
db_dir: databases

# These directories are relative to your theme directory.
# An in value of 'assets/coffee' will expand to:
# 'content/themes/<themename>/assets/coffee'
coffeescript:
  in: assets/coffee
  out: assets/js

development:
  database:
    name: name
    user: user
    pass: pass
    host: host
    
staging:
  deploy:
    user: user
    host: host
    directory: dir
    
  database:
    name: name
    user: user
    pass: pass
    host: host
    
production:
  deploy:
    user: user
    host: host
    directory: dir
    
  database:
    name: name
    user: user
    pass: pass
    host: host